// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVYFUlvYTfGPqgvkcp9K6It_AABbZfME',
    appId: '1:485014065632:web:ed981953f459045c021b85',
    messagingSenderId: '485014065632',
    projectId: 'fitbit-2763f',
    authDomain: 'fitbit-2763f.firebaseapp.com',
    storageBucket: 'fitbit-2763f.appspot.com',
    measurementId: 'G-BBXCXHJJH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmTWTyAjI2cDcA0kozKDqSo54RgXcCJBc',
    appId: '1:485014065632:android:06c4496dec6a657d021b85',
    messagingSenderId: '485014065632',
    projectId: 'fitbit-2763f',
    storageBucket: 'fitbit-2763f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdhxCJQOOEPTHzNMxAzpCCxMSA8HTnZwE',
    appId: '1:485014065632:ios:270d6c3abe906161021b85',
    messagingSenderId: '485014065632',
    projectId: 'fitbit-2763f',
    storageBucket: 'fitbit-2763f.appspot.com',
    iosBundleId: 'com.example.fitBit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdhxCJQOOEPTHzNMxAzpCCxMSA8HTnZwE',
    appId: '1:485014065632:ios:cb091237083adca2021b85',
    messagingSenderId: '485014065632',
    projectId: 'fitbit-2763f',
    storageBucket: 'fitbit-2763f.appspot.com',
    iosBundleId: 'com.example.fitBit.RunnerTests',
  );
}
