// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwQVlJk22udEVKaZuMjpKBy6kWEunLJJw',
    appId: '1:617009152460:web:8c25b7801fc4cf4ba11d69',
    messagingSenderId: '617009152460',
    projectId: 'kriyetaaa',
    authDomain: 'kriyetaaa.firebaseapp.com',
    storageBucket: 'kriyetaaa.appspot.com',
    measurementId: 'G-QPGPKVR0VL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHRieA5_fz0ZFRwgY-4_g8ApcX9y3zrmc',
    appId: '1:617009152460:android:25c3786c989e2c9ba11d69',
    messagingSenderId: '617009152460',
    projectId: 'kriyetaaa',
    storageBucket: 'kriyetaaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowJxnqIPMdMRy2055H1b0xE46Vume-jA',
    appId: '1:617009152460:ios:f3000d84fa47acbda11d69',
    messagingSenderId: '617009152460',
    projectId: 'kriyetaaa',
    storageBucket: 'kriyetaaa.appspot.com',
    iosBundleId: 'com.example.kriyeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBowJxnqIPMdMRy2055H1b0xE46Vume-jA',
    appId: '1:617009152460:ios:7aa0626941d0d637a11d69',
    messagingSenderId: '617009152460',
    projectId: 'kriyetaaa',
    storageBucket: 'kriyetaaa.appspot.com',
    iosBundleId: 'com.example.kriyeta.RunnerTests',
  );
}
